services:
  app:
    image: request-monitor:v1
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
#    restart: always
    volumes:
      - ./mongo-data:/data/db